MainApp/urls.py
from django.urls import path

from . import views

app_name =  'MainApp'

urlpatterns = [
    path('',views.index, name='index'),
    path('topics',views.topics, name='topics'),
    path('topics/<int:topic_id>/',views.topic, name="topic"), #creating the individual topic pages that navigates through topics page-creates an integer variable that references the primary keys of topics table
    path('new_topic/',views.new_topic, name="new_topic"),
    path('new_entry/<int:topic_id>/',views.new_entry, name="new_entry"),
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('MainApp.urls')),  #use '' because referencing homepage
    path('users/',include('users.urls')), #include all urls in the mainapp and users folders
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('',include('django.contrib.auth.urls')), #URLs that handle user accounts are part of django framwork, we don't have to create them
    path('register/', views.register,name='register'),
]

MainApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)   #owner field is a foregin key to user
                                                                #each topic is only assigned to one user

    def __str__(self):
        return self.text

class Entry(models.Model):   #has fields called topic, text, and date_added
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'
        #allows us to set a special attribute telling Django to use entries
        #when it's referring to multiple entries
    
    def __str__(self):
        return f"{self.text[:50]}..."  #changes the title from "Entry 1" to a short description

users/models.py
from django.db import models

# Create your models here.

MainApp/forms.py
from django import forms

from .models import Entry, Topic    #create form for topic where user can add topic


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']     #don't have to show all fields from topic model
        labels = {'text':''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':''}
    

MainApp/views.py
from django.shortcuts import redirect, render
from .models import Topic
from .forms import TopicForm
from .forms import EntryForm
from .models import Topic, Entry
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404

# Create your views here.
def index(request):      #don't need login required because this is the only place you can access the login button
    '''The home page for Learning Log'''
    return render(request, 'MainApp/index.html')


@login_required
def topics(request):        #whatever you called it in urls must be the same
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')  #calls the topics template
    
    context = {'topics':topics} #populating the template with the data
                                #using a DICTIONARY
                                    #key- variable used in the template file
                                    #value- variable used in the view function
    
    return render(request, 'MainApp/topics.html',context)


@login_required
def topic(request,topic_id):     #what you name in url file must be received in views file
    topic = get_object_or_404(Topic, id=topic_id)
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.all()        #from myshell.py file

    context = {'topic':topic, 'entries':entries}  #key represents a variable name to use in template
                                                  #value reprsents a variable name to use in views
    return render(request, 'MainApp/topic.html',context)


@login_required
def new_topic(request):
    if request.method != 'POST':    #if get request
        form = TopicForm()          #loads an empty form
    else:
        form = TopicForm(data=request.POST)  #if post request, take data from webpage and save it in form

        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()

            return redirect('MainApp:topics')

    context = {'form':form}         #interview q- context is a dict that allows us to pass data to the html file
    return render(request, 'MainApp/new_topic.html',context)


@login_required
def new_entry(request,topic_id):           #******* interview q - url.py file has a variable called topic_id, so we must use the same variable
                                           #or else the website will crash
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
                                                #form we're creating only gives the text field, date_added field from models is automatically generated
        if form.is_valid():
            new_entry = form.save(commit=False) #tells database we're not ready to write to it yet
            new_entry.topic = topic             #assigns entry to a topic
            new_entry.save()

            return redirect('MainApp:topic',topic_id=topic_id)

    context = {'form': form, 'topic':topic}
    return render(request, 'MainApp/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    '''Edit an existing entry'''
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('MainApp:topic', topic_id=topic.id)
        
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'MainApp/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)   #request is post- write to the database
        if form.is_valid():
            new_user = form.save()
            login(request,new_user)   #login the new user that was just created
            return redirect('MainApp:index')
    
    context = {'form':form}
    return render(request,'registration/register.html',context)

MainApp/templates/mainapp/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,shrink-to-fit=no">
    <title>Learning Log</title>

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'MainApp:index'%}">Learning Log</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
        aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'MainApp:topics'%}">Topics</a></li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="navbar-text">Hello, {{ user.username }}.</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
                {% endif %}
            </ul>
        </div>

    </nav>
<main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
    </div>
    <div>
        {% block content %}{% endblock content %}
    </div>
</main>
</body>
</html>

MainApp/templates/mainapp/edit_entry.html
{% extends "MainApp/base.html" %}

{% block content %}

<p><a href="{% url 'MainApp:topic' topic.id %}">{{ topic }}</a></p>
<!--includes topic_id value in the URL so the view function can associate the new entry with the correct topic-->
<!--user can click on this to get back to the topic they were in-->

<p>Edit entry:</p>:</p>

<form action="{% url 'MainApp:edit_entry' entry.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">Save Changes</button>

</form>

{% endblock content %}

MainApp/templates/mainapp/index.html
{% extends "MainApp/base.html" %}

{% block page_header %}

<div class="jumbotron">
    <h1 class="display-3">Track your learning</h1>
    <p class="lead">Make your own Learning Log, and keep a list of the topics you're learning about. 
        Whenever you learn something new about a topic, make an entry summarizing what you've learned.</p>
    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">Register &raquo;</a>
</div>

{% endblock page_header %}

MainApp/templates/mainapp/new_entry.html
{% extends "MainApp/base.html" %}

{% block content %}

<p><a href="{% url 'MainApp:topic' topic.id %}">{{ topic }}</a></p>
<!--includes topic_id value in the URL so the view function can associate the new entry with the correct topic-->
<!--user can click on this to get back to the topic they were in-->

<p>Add a new entry:</p>

<form action="{% url 'MainApp:new_entry' topic.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">Add entry</button>

</form>

{% endblock content %}

MainApp/templates/mainapp/new_topic.html
{% extends "MainApp/base.html" %}

{% block content %}

<p>Add a new topic:</p>

<form action="{% url 'MainApp:new_topic' %}" method="post">
    {% csrf_token %}   <!--prevents SQL injection hacks-->

    {{ form.as_p }}    <!--don't have to write out each field, just load form-->

    <button name="submit">Add topic</button>

</form>

{% endblock content %}

MainApp/templates/mainapp/topic.html
{% extends "MainApp/base.html" %}

{% block page_header %}
<h3>{{ topic }}</h3>        <!--pulled from context in views-->
{% endblock page_header %}


{% block content %} 

{% for e in entries %}   <!--go to models to see the attribute list-->
<div class="card mb-3">
    <h4 class="card-header">
        {{ e.date_added|date:'M d, Y H:i' }}
        <small><a href="{% url 'MainApp:edit_entry' e.id %}">Edit entry</a></small>
    </h4>
<div class="card-body">
    {{ e.text|linebreaks }}           <!--want e.text because str method in models only returns 50 characters-->
</div>
</div>

{% empty %}
<p>There are no entries for this topic yet.</p>
{% endfor %}


<p>
    <a href="{% url 'MainApp:new_entry' topic.id %}">Add a new entry</a>
</p>

{% endblock content %}

MainApp/templates/mainapp/topics.html
{% extends "MainApp/base.html" %}

{% block page_header %}
<h1>Topics</h1>
{% endblock page_header %}


{% block content %}

<ul> 
    {% for t in topics %}  <!--Calls the key of the topics dictionary in views.py, iterates throguh the dict-->
    <li><h3>
        <a href="{% url 'MainApp:topic' t.id %}">{{ t }}</a>
    </h3></li>           <!--Adds the topic to the list  (*****add t.date_added attribute if you want to display date)
                         --only need "t" for text because of str method in models-->
    {% empty %}
    <li><h3>No topics have been added yet.</li></h3>
    {% endfor %}

</ul>

<h3><a href="{% url 'MainApp:new_topic' %}">Add a new topic</a></h3>
    

{% endblock content %}

learning_log/templates/505.html
{% extends "MainApp/base.html" %}

{% block page_header %}
<h2>There has been an internal error. (500)</h2>
{% endblock page_header %}